### ISSUE TITLE
make errors - ubuntu 14.04, ozw 1.2.919

### ISSUE THREAD

**Issue by skiv71** [OpenZWave/open-zwave-control-panel#33]
Hi,

I've been trying to build ozwcp on the above platform, but I'm seeing errors.

Do I need to use the older ozw version?

Thanks

Neil

------------------------------------------

g++ -c -Wall -Wno-unknown-pragmas -Wno-inline -Werror -Wno-format -g -DDEBUG -ggdb -O0 -I ../open-zwave/cpp/src -I ../open-zwave/cpp/src/command_classes/ -I ../open-zwave/cpp/src/value_classes/ -I ../open-zwave/cpp/src/platform/ -I ../open-zwave/cpp/src/platform/unix -I ../open-zwave/cpp/tinyxml/ -I ../libmicrohttpd/src/include -o ozwcp.o ozwcp.cpp
In file included from ozwcp.cpp:55:0:
ozwcp.h:103:47: error: ‘InstanceAssociation’ has not been declared
   void addGroup(uint8 node, uint8 g, uint8 n, InstanceAssociation *v);
                                               ^
ozwcp.cpp:217:54: error: ‘InstanceAssociation’ has not been declared
 void MyNode::addGroup (uint8 node, uint8 g, uint8 n, InstanceAssociation *v)
                                                      ^
ozwcp.cpp: In member function ‘void MyNode::addGroup(uint8, uint8, uint8, int*)’:
ozwcp.cpp:227:14: error: request for member ‘m_instance’ in ‘*(v + ((sizetype)(((unsigned int)i) * 4u)))’, which is of non-class type ‘int’
     if (v[i].m_instance == 0)
              ^
ozwcp.cpp:228:36: error: request for member ‘m_nodeId’ in ‘*(v + ((sizetype)(((unsigned int)i) * 4u)))’, which is of non-class type ‘int’
      snprintf( str, 32, "%d", v[i].m_nodeId );
                                    ^
ozwcp.cpp:230:39: error: request for member ‘m_nodeId’ in ‘*(v + ((sizetype)(((unsigned int)i) * 4u)))’, which is of non-class type ‘int’
      snprintf( str, 32, "%d.%d", v[i].m_nodeId, v[i].m_instance );
                                       ^
ozwcp.cpp:230:54: error: request for member ‘m_instance’ in ‘*(v + ((sizetype)(((unsigned int)i) * 4u)))’, which is of non-class type ‘int’
      snprintf( str, 32, "%d.%d", v[i].m_nodeId, v[i].m_instance );
                                                      ^
ozwcp.cpp: In member function ‘void MyNode::updateGroup(uint8, uint8, char*)’:
ozwcp.cpp:288:70: error: no matching function for call to ‘OpenZWave::Manager::AddAssociation(uint32&, uint8&, uint8&, int&, int&)’
    Manager::Get()->AddAssociation(homeId, node, grp, nodeId, instance);
                                                                      ^
ozwcp.cpp:288:70: note: candidate is:
In file included from ozwcp.cpp:48:0:
../open-zwave/cpp/src/Manager.h:1359:8: note: void OpenZWave::Manager::AddAssociation(uint32, uint8, uint8, uint8)
   void AddAssociation( uint32 const _homeId, uint8 const _nodeId, uint8 const _groupIdx, uint8 const _targetNodeId );
        ^
../open-zwave/cpp/src/Manager.h:1359:8: note:   candidate expects 4 arguments, 5 provided
ozwcp.cpp:300:73: error: no matching function for call to ‘OpenZWave::Manager::RemoveAssociation(uint32&, uint8&, uint8&, int&, int&)’
    Manager::Get()->RemoveAssociation(homeId, node, grp, nodeId, instance);
                                                                         ^
ozwcp.cpp:300:73: note: candidate is:
In file included from ozwcp.cpp:48:0:
../open-zwave/cpp/src/Manager.h:1372:8: note: void OpenZWave::Manager::RemoveAssociation(uint32, uint8, uint8, uint8)
   void RemoveAssociation( uint32 const _homeId, uint8 const _nodeId, uint8 const _groupIdx, uint8 const _targetNodeId );
        ^
../open-zwave/cpp/src/Manager.h:1372:8: note:   candidate expects 4 arguments, 5 provided
ozwcp.cpp: In function ‘void OnNotification(const OpenZWave::Notification*, void*)’:
ozwcp.cpp:516:4: error: ‘InstanceAssociation’ was not declared in this scope
    InstanceAssociation *v = NULL;
    ^
ozwcp.cpp:516:25: error: ‘v’ was not declared in this scope
    InstanceAssociation *v = NULL;
                         ^
ozwcp.cpp:522:15: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
     delete [] v;
               ^
ozwcp.cpp:749:9: error: ‘Type_ControllerCommand’ is not a member of ‘OpenZWave::Notification’
    case Notification::Type_ControllerCommand:
         ^
make: *** [ozwcp.o] Error 1

**Comment by Fishwaldo** [comment]
you need to build against the current snapshots of OZW, not the stable releases.
