### ISSUE TITLE
Bootstrap CSS interface

### ISSUE THREAD

**Issue by WoLpH** [OpenZWave/open-zwave-control-panel#35]
Hi guys,

I've been working on a bootstrap based interface for ozwcp and I was wondering, if it's done and completely functioning, would you guys be interested in merging it?

I'm not 100% done yet however and the changes are quite significant due to indentation changes:
https://github.com/OpenZWave/open-zwave-control-panel/compare/master...WoLpH:master
The plan is to replace most of the javascript as well with some simpler jquery based operations.

It is currently functional as far as I am aware, although there is a possibility that I broke some things along the process.

**Comment by Fishwaldo** [comment]
of course. No one here is a real HTML guy, so any improvements to freshen up the interface would be great :)

**Comment by Fishwaldo** [comment]
when your ready, please create a PR.

**Comment by WoLpH** [comment]
Awesome, I'll link this issue with the pull request.

The results for the time being:
![image](https://cloud.githubusercontent.com/assets/270571/9980781/ea9b394a-5fa5-11e5-8964-09e30d81c78d.png)

**Comment by satzg** [comment]
Looks good! Thanks for working on it.

Thanks,
Greg

**Comment by Fishwaldo** [comment]
hows this going?

**Comment by WoLpH** [comment]
The current version is working but it's not completely done yet, just haven't had much time to work on it. I hope to have some time again in a week or two

**Comment by WoLpH** [comment]
Well, there's always more to add but it's already a big improvement imho.

Ideally the javascript would get a bit of a rewrite too, but that's too big of a project right now.
It's a pretty hefty change but I think it's an improvement: https://github.com/OpenZWave/open-zwave-control-panel/compare/master...WoLpH:master?w=1
