### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by DonOregano** [OpenZWave/open-zwave-control-panel#49]
What is the license of this code?

Adding a LICENSE file to the top level would be good.

(I'm making an Arch Linux AUR package of this, and it needs to know...)

**Comment by haklein** [comment]
The license can be seen in the top section of the source code

**Comment by DonOregano** [comment]
Hmm, well, that only tells me the licensing info for that file, really. I'd like to "know" that the license covers everything in the repo. But adding info to that effect in the readme would be fine (pointing to the source file).

**Comment by DonOregano** [comment]
And, also, what license is that actually? I like to be able to check what other people think of different licences by googling, e.g. "mit license".

**Comment by haklein** [comment]
all .cpp/.h files have that license.

Greg is not active with OZW anymore, so you might want to catch him via email.

**Comment by DonOregano** [comment]
Oh, ok.

**Comment by haklein** [comment]
I've added a LICENSE file with Greg's licensing information. I'm sure that this matches his intentions.

**Comment by DonOregano** [comment]
Well, I would consider this issue closed then!
